### PR TITLE
Ensure that pullToRefreshView stops observing scrollView properties.

### PR DESCRIPTION
**Pull request by chapados**
Since the SVPullToRefreshView holds a weak reference to the scrollView,
it is possible for the scrollView to be nil by the time dealloc is called.
This situation leaks Key-Value Observers, triggering a runtime warning,
and leading to a potential crash.

These changes attempt to ensure that scrollView observers are added & removed
whenever the pullToRefresh view changes, and also during init/dealloc.

### CODE REVIEW

**Comment by samvermette** [comment]
@chapados in which case would the UIScrollView get released but not the SVPullToRefreshView (since it's a subview of the scroll view). Also, you make a check in `addPullToRefreshWithHandler:` to make sure the scroll view didn't already have a pull to refresh view assigned to it... don't see much of a point there either. Is this just to be on the safe side?

**Comment by chapados** [comment]
@samvermette I created a demo project to expose the bug: https://github.com/chapados/SVPullToRefreshDemo
I originally ran into this issue when using ViewDeck, but it also occurs in a navigation stack. 
After creating this test project, I realized that this patch does not resolve the issue in this case ;-)  Instead of my original patch, I can resolve the KVO leak by changing the scrollView property to unsafe_unretained, and also make sure to stop observing the 'frame' property of the scrollView.

```
 diff --git a/SVPullToRefresh/SVPullToRefresh.m b/SVPullToRefresh/SVPullToRefresh.m
 index 379313a..d95a67e 100644
 --- a/SVPullToRefresh/SVPullToRefresh.m
 +++ b/SVPullToRefresh/SVPullToRefresh.m
 @@ -38,7 +38,7 @@ typedef NSUInteger SVPullToRefreshState;
  @property (nonatomic, strong, readonly) UILabel *dateLabel;
  @property (nonatomic, strong, readonly) NSDateFormatter *dateFormatter;

 -@property (nonatomic, weak) UIScrollView *scrollView;
 +@property (nonatomic, unsafe_unretained) UIScrollView *scrollView;
  @property (nonatomic, readwrite) UIEdgeInsets originalScrollViewContentInset;

  @end
 @@ -56,6 +56,7 @@ typedef NSUInteger SVPullToRefreshState;

  - (void)dealloc {
      [self.scrollView removeObserver:self forKeyPath:@"contentOffset"];
 +    [self.scrollView removeObserver:self forKeyPath:@"frame"];
  }

  - (id)initWithScrollView:(UIScrollView *)scrollView {
```

Alternatively, I can resolve this issue by removing KVO in the dealloc method of the tableViewController.

``` objective-c
    - (void)dealloc
    {
        [self.tableView removeObserver:self.tableView.pullToRefreshView forKeyPath:@"contentOffset"];
        [self.tableView removeObserver:self.tableView.pullToRefreshView forKeyPath:@"frame"];
    }
```

Maybe I'm doing something stupid.

**Comment by samvermette** [comment]
Totally had forgotten to remove the observer from `frame` in dealloc. Just pushed a fix for this.

Not sure what's the difference between `weak` and `unsafe_unretained` but I trust you on this one and pushed the change. Let me know if that solves it.

**Comment by samvermette** [comment]
Closing this for now as I haven't heard back from you, hopefully my commit did the trick. Thanks!

**Comment by chapados** [comment]
Yes, sorry I forgot to cycle back on this. Your commit fixed the problem. Thanks.

**Pull request closed without merging**
