### PR TITLE
Expose titleLabel for customization. Increase titleLabel width to allow ...

### PR DESCRIPTION
**Pull request by romanr**
...longer localized strings.

### CODE REVIEW

**Comment by samvermette** [comment]
@romanr This is nice, but how do you deal with the dif status changes? Or was the intent of this only to customize the "Loading" status message?

**Comment by romanr** [comment]
What do you mean by "dif status changes" ?

**Comment by samvermette** [comment]
@romanr right now SVPullToRefresh has 3 status strings: "Pull down to refresh", "Release to refresh", "Loading". These are set within SVPullToRefresh depending on the scroll view's content offset. Therefore setting the `titleLabel.text` property is only temporary, since SVPullToRefresh is gonna keep changing the status string by itself... Are you only setting that property inside the refreshHandler (i.e. only overriding the "Loading" status message)?

**Comment by samvermette** [comment]
You can now use setTitle:forState: to customize the statuses.

**Pull request closed without merging**
