### PR TITLE
Ability to Hide the Pull to Refresh View

### PR DESCRIPTION
**Pull request by Hackmodford**
I added a BOOL called hidePullToRefresh that when set TRUE will hide the pull to refresh.
I also added this feature to the demo.

### CODE REVIEW

**Comment by samvermette** [comment]
Why making this a property instead of removing it completely using a method like `removePullToRefresh` on the UIScrollView extension? So you don't have to set the action handler again?

If that's the case, then a custom `hidden` setter would be more appropriate (`hidePullToRefresh` is more of a method name than a property name...)

**Comment by Hackmodford** [comment]
I think it is a bettery idea to use a property instead of a remove method so that you do not have to set up the pullToRefresh twice (that's kinda the philosophy of this right? One line of code?)

I also renamed the property to showsPullToRefresh after reading the apple documentation 
https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingIvarsAndTypes.html#//apple_ref/doc/uid/20001284-BAJGIIJE

Let me know if this is acceptable

**Comment by samvermette** [comment]
Right, makes sense. Still, `showsPullToRefresh` should be a property on the `UIScrollView` extension, not on SVPullToRefresh itself. And from that setter you would hide the pull to refresh view...

**Comment by Hackmodford** [comment]
I tried to do what you suggested but I am unclear on how to do it. I'm new to programming.
I've added it as a UIScrollView extension property. But when I try to access it in the showsPullToRefresh set state method I get an error. I'm trying to do it like this [self.scrollview showsPullToRefresh] is there a different way to acess the property? Or am I doing it wrong? I had to use dynamic instead of synthesize for the property.

**Comment by Hackmodford** [comment]
Yeah I can't access the new property from anywhere apparently.

**Comment by Hackmodford** [comment]
Wow that took me a while to wrap my head around what @dynamic required me to do. Will these changes be acceptable?

**Comment by Hackmodford** [comment]
Had to clean up some old stuff... This should be acceptable now.

**Comment by Hackmodford** [comment]
Is there anything I need to change?

**Comment by samvermette** [comment]
@Hackmodford sorry, this pull request has become a mess (14 commits!) and can't even be merged automatically. Can you resubmit this as a pull request with only 1 or 2 commits please?

**Comment by Hackmodford** [comment]
I will do as you suggest

**Pull request closed without merging**
