### PR TITLE
Fix retain cycle

### PR DESCRIPTION
**Pull request by twobitlabs**
Sam, nice work on this. One problem, which I've found in nearly all PTR implementations, is that you have a retain cycle. I updated the demo code to reference the SVPullToRefresh in a __block variable. Otherwise the controller gets retained when the block is copied, and it will never be released.

I also made the scrollView property weak instead of strong. The scroll view retains SVPullToRefresh in its subviews array. If SVPullToRefresh also retains the scrollView, neither will ever be released.

The problem is easy to reproduce in the Allocations instrument. Just tap the launch button, navigate back up, rinse, repeat. You'll see new instances SVController, SVPullToRefresh, and UITableView every time you launch the controller, which are never deallocated.

### CODE REVIEW

**Comment by samvermette** [comment]
All good calls. Yeah it's probably safe to put a more complete example in the demo, with the `__block` variable and all. However it bugs me that 90% of the time you're gonna have to assign `self` to a `__block` variable...  is there a way we could avoid this by changing how the block is handled or copied? Maybe passing the pullToRefreshView as a block argument? but then what about `self`? Say in my block I do `[self fetchNewData]`.

**Comment by twobitlabs** [comment]
Good point. Assigning `self` to a `__block` variable creates the same retain cycle. Let me think about it some more.

**Comment by twobitlabs** [comment]
I haven't come up with an approach that will work well with blocks. But given that the block content is likely to be a single method call, like [self fetchNewData], I tried a target:action: approach. It may not be as sexy as blocks, but it works well, avoids the retain cycle, and keeps it a one-liner. Take a look at https://github.com/twobitlabs/SVPullToRefresh/commit/2c3bff8671382c2b82850483ca2b202476d6d22b.

**Comment by samvermette** [comment]
Yeah the target:action: approach is definitely not a sexy as blocks... and I'd like to have it work only one way. I just pushed a commit that fixes the `scrollView` retain cycle but will keep looking as far as the `__block` thing goes... Thanks!

**Comment by twobitlabs** [comment]
Sam, I don't know why this didn't strike me before, but all you need is a __weak reference to pass into the block. I've updated the commit at https://github.com/twobitlabs/SVPullToRefresh/commit/6f9867333a7b8bc675cdc4fa04b82ebb1915c634, which allows for the block style but fixes the retain cycle.

**Comment by jwilling** [comment]
With ARC, the `__block` specifier still creates retain cycles.  A `__weak` specifier is needed if you do not wish to retain the variable.  I don't believe this was documented in the transition notes.

**Comment by twobitlabs** [comment]
@jwilling correct, that's why I updated the sample code to use a `__weak` specifier on the reference to self used in the block.

**Comment by samvermette** [comment]
That's good to know, I'll add it to the demo project so people know how to prevent the retain cycle.

That being said, I was looking for a solution where you don't even have to assign `self` to a `weak` variable (since 99% of the time you're gonna end up using `self` inside that action handler).

**Comment by jwilling** [comment]
That is, unfortunately, the drawback to blocks at the moment.  Here's to hoping that a future version of Clang will support automatic weak references for any reference to `self` inside a block.  Time to file a radar!

**Pull request closed without merging**
