### PR TITLE
Update the readme to show how to use -fobjc-arc with IOS4

### PR DESCRIPTION
**Pull request by emile818**
http://stackoverflow.com/questions/8112035/libobjc-a-dylib-compile-error-on-ios-4-3

### CODE REVIEW

**Comment by samvermette** [comment]
@emile818 good find. I'd like to add this to all of my SV classes READMEs, but I'm a bit confused. How come you add the flag to Build Settings > Other Linker Flags instead of only to the class files that use ARC? What is the `-fobjc-arc` flag supposed to do when added to the whole project instead of specific files?

**Comment by emile818** [comment]
@samvermette  That was my original intension to add this to all the READMEs.
I was confused as well my project is mrc and it was failing with all of your arc plugins(HUD, segmented and pulldown) when using the -fobjc-arc compiler flag until i added -fobjc-arc to the Settings > Other Linker Flags.
When i tested the arc demo project it worked so i researched it and i found this, i tested 4.3 so far and i am going to test other IOS4 versions.
Maybe apple can answer this !!!

**Comment by samvermette** [comment]
@emile818 so do you have to add the compiler flag to **both** places on iOS 4 or only in Settings > Other Linker Flags?

**Comment by emile818** [comment]
@samvermette you need to add the flag to both places
If you add it only to the .m you will receive  a "dyld: lazy symbol binding failed: Symbol not found: _objc_retain" + crash

**Comment by samvermette** [comment]
I have tried using this flag for the past 3 months and it's been giving me a lot of issues, especially when converting a project to ARC. I decided to not bother adding this check, and just hope that people already use ARC and/or will read the README (I'm also getting lesser and lesser reports about this, I suppose because more and more people use ARC).

**Pull request closed without merging**
