### PR TITLE
Add ability to remove pull-to-refresh from scroll view

### PR DESCRIPTION
**Pull request by johntmcintosh**
Sam, I came across the need today to be able to add and remove the pull-to-refresh functionality from a scroll view based on a user preference. The code in this pull request allowed me to easily do that. If you don't have any concerns with this approach, I'd love to see this merged into the master branch. If you do have concerns, I'm happy to update and send a different pull.

Thanks for sharing this great component with us!

john

### CODE REVIEW

**Comment by samvermette** [comment]
Sorry for the late reply. Does this do anything different than setting `showsPullToRefresh` to `NO`?

**Comment by johntmcintosh** [comment]
At the time I had tried setting `showsPullToRefresh` to `NO`, but now I'm getting the same result either way. Let's just close this for now and I'll reopen it if I realize why the difference was necessary. Sorry for the confusion!

**Comment by hhartz** [comment]
@samvermette I need to have different pull to refresh behavior and appearance for the same view given different preconditions (filtering). In this case I need to replace the pullToRefreshView with a new one using different blocks and changed label titles. Is that achievable without this pull request?

**Comment by hhartz** [comment]
@samvermette actually, this seems achievable without the patch by using

```
[_table.pullToRefreshView removeFromSuperview];
[_table setValue:nil forKey:@"pullToRefreshView"];
```

**Pull request closed without merging**
