### PR TITLE
Add support for setting UIActivityIndicatorView color (iOS 5+)

### PR DESCRIPTION
**Pull request by bdbergeron**
Considering everything else can be customized, I figured it would be nice to add support for setting a custom color for the UIActivityIndicatorView so that user's aren't constrained to either white or gray.

### CODE REVIEW

**Comment by fjcaetano** [comment]
+1

**Comment by fcavedon** [comment]
+1

**Comment by leoreisbk** [comment]
+1

**Comment by jxdwinter** [comment]
+1 and how to use this patch? Thank you. @bdbergeron

**Comment by michelzanini** [comment]
+1

**Comment by JRG-Developer** [comment]
@jxdwinter http://chem-bla-ics.blogspot.com/2011/01/github-tip-download-commits-as-patches.html
You can also apply patch with many common Git GUI software, like SourceTree for example.

**Comment by samvermette** [comment]
Merged. Sorry it took so long guys.

**Pull request merged**
