### PR TITLE
Hide infinite scroll activity indicator by scrolling to the bottom most row of a table view

### PR DESCRIPTION
**Pull request by exalted**

### CODE REVIEW

**Comment by samvermette** [comment]
Not sure what this is supposed to do? If your infiniteScrollingHandling is adding to your tableview, then the activity indicator will automatically be moved down out of the viewport. Does that make sense?

**Comment by exalted** [comment]
What I actually get is that when you scroll bottom of the table view activity indicator will show up as an additional row at the very bottom of the table view, but then if you have nothing left to add to the table view or if you do update data source and reload data, then activity indicator's additional row will stick there.

**Comment by samvermette** [comment]
Oh I see. In such cases, you can get rid of the infinite scrolling view by setting `showsInfiniteScrolling` to `NO` on the scroll view.

**Comment by samvermette** [comment]
I don't think this worked in previous versions, so make sure to pull the refactor I pushed 2 days ago.

**Comment by exalted** [comment]
Well, I should first check your latest changes, but I still believe there must be a subtle difference what I pull–requested and what `showsInfiniteScrolling` actually does: suppose you make a new HTTP request when infinite scroll action fires up, but then you get "empty" response, thus "hide" infinite scroll. Then how would you suggest a developer re–issue a request to see if is there anything new when user insists scrolling to the bottom of the a table view for instance?

P.S.: No offense, I am not sure why you consider this issue closed, I generally believe the person opened the issue should be the one who decides that is closed.

**Comment by samvermette** [comment]
I've taken a (maybe bad) habit of closing issues myself as otherwise some end up staying open for weeks/months.

Regarding your particular issues, I don't think scrolling back to the last row of the table view is the right feedback to have for an empty response.
- Unlike pull to refresh, infinite scroll usually pulls items **from the past**. There's no reason a response would return empty and then later return content. Once the request returns empty, it's usually the end of that content feed.
- I'm not sure scrolling back to the last row makes it clear to the user about what just happened. Instead, I would use `setCustomView:forState:` (new in the refactor) to replace the activity indicator with a "dot image" that (imo) better communicates that this is the finish line. As I come to think of it, support for this might still be rough on the edges as the action handler will keep getting called, and that setting `showsInfiniteScrolling` to `NO` will hide the infinite scrolling view completely. 

I will leave this issue opened until the last point I mentioned is fixed, but I definitely don't think scrolling back to the last row is the appropriate feedback for an empty/failed infinite scrolling request. Furthermore, your implementation only works with UITableView (infinite scrolling now works with UIScrollView as well).

**Comment by exalted** [comment]
Well, I guess I agree to that. Looking forward to it...

Cheers,

**Comment by samvermette** [comment]
Just added an `enabled` property to SVInfiniteScrolling.

So, say you would want to display that "dot image" to communicate that there is no more content, you would do:

```
self.tableView.infiniteScrollingView.enabled = NO;
```

After making sure that you did set a custom view for the `SVInfiniteScrollingStateStopped` state:

```
[self.tableView.infiniteScrollingView setCustomView:dotImage forState:SVInfiniteScrollingStateStopped];
```

As I come to think of it, I should probably have that dot built-in by default. Will leave the issue open until I do.

**Comment by exalted** [comment]
Sounds like nobody can stop you right now... ;-) Thanks.

**Comment by exalted** [comment]
@samvermette I realize this ain’t gonna be merged after all. Close it perhaps? Thanks.

**Pull request closed without merging**
