### PR TITLE
Fixes for several compiler warnings

### PR DESCRIPTION
**Pull request by jessedc**
My default compiler warnings brought up some fairly trivial issues when I compiled SVPullToRefresh. They were straight forward to fix/suppress so I thought I'd send along a PR. 

Included are fixes for -Wsign-conversion, -Wfloat-equal, -Wconversion and -Wnewline-eof. 

There are no functional changes and I've only updated the main four SVPullToRefresh/Infinite scroll files as I wasn't concerned with the demo project.

### CODE REVIEW

**Comment by samvermette** [comment]
Just curious, how come you get these warnings and I don't?

**Comment by jwilling** [comment]
@samvermette Sorry for asking the obvious, but did you enable the compiler flags he mentioned? They're not on by default.

**Comment by jessedc** [comment]
@samvermette the warnings are not enabled by default, and I have setup some xcode configurations that enable a relatively strict set of errors. The ones I've fixed come up a lot in third party code but are fairly trivial to fix.

You can turn them on by adding them to the WARNING_CFLAGS compiler option

WARNING_CFLAGS = -Wfloat-equal -Wconversion -Wnewline-eof -Wsign-conversion

**Comment by samvermette** [comment]
Hah, didn't read your initial post carefully. Sorry about that.

**Pull request merged**
