### PR TITLE
make the dateLabel property public

### PR DESCRIPTION
**Pull request by caiguo37**
If you want to set dateLabel text like "2 mins ago",you'll need to directly set dateLabel.

### CODE REVIEW

**Comment by samvermette** [comment]
@caiguo37 I think it would make more sense to instead have a `showRelativeDate` property, and so SVPullToRefresh automatically takes care of formatting that string.

**Comment by caiguo37** [comment]
I think a `dateString` property is easier and SVPullToRefresh doesent need to take care of this.
User can choose to set `dateString` directly or set `lastUpdatedDate`.
BTW,Matt has done some great work about format date: https://github.com/mattt/FormatterKit.

**Comment by samvermette** [comment]
You're right that it shouldn't be SVPullToRefresh's job to format the date _at all_ actually. I probably should have exposed `dateLabel` from the start, and never have a `lastUpdatedDate` property, as SVPullToRefresh should only focus on the UI. I'll think about deprecating `lastUpdatedDate` in the near future.

Thanks for sharing your thoughts and the link to FormatterKit.

**Comment by BenoitVerdier** [comment]
I agree that it's up to the developer to format the last refresh date and set the subtitle but it would be useful to keep the lastUpdatedDate in SVPullToRefresh.
It's always interesting to keep around the last time the component got updated (not only for display but also to do some basic checking against it), and it's not something that I want to copy and paste in every view that uses the component.

**Pull request merged**
