### PR TITLE
Added option for pull to refresh from bottom

### PR DESCRIPTION
**Pull request by gabro**
Added `-addPullToRefreshWithActionHandler:position:` which takes a `SVPullToRefreshPosition` as second parameter.

`SVPullToRefreshPosition` may be either:
- `SVPullToRefreshPositionTop` : pull to refresh from the top of the scroll view (the current behavior)
- `SVPullToRefreshPositionBottom` : pull to refresh from the bottom of the scroll view

`-addPullToRefreshWithActionHandler:` defaults on `SVPullToRefreshTop`, making this update fully backward compatible.

---

Example

```
[self.tableView addPullToRefreshWithActionHandler:^{
   // ...
} position:SVPullToRefreshPositionBottom];
```

will result in the following behavior

SVPullToRefresh from bottom

### CODE REVIEW

**Comment by samvermette** [comment]
Nice work on the code itself, but pull to refresh at the bottom of a table view is very unusual and doesn't really make sense in my opinion. Infinite scrolling is a lot more appropriate. For the sake of keeping SVPullToRefresh as simple as possible, I'm declining this PR, sorry.

**Comment by gabro** [comment]
I understand your point of view.

Anyway, the reason why I developed this modification is the simple case in which you have a stream of content going from the top to the bottom, i.e. older content is at the top (in my case a list of comments for a topic).

In such a case, the most natural interaction would be to refresh from the bottom and to have infinite scrolling at the top (I'm on my way of developing that one too).

To wrap it up, this is the way I perceive it:
- **Infinite scrolling**: fetch older content
- **Pull to refresh**: update with newer content

So everything depends on how the content is ordered. While I agree that the most common case is having old content at the bottom, I think it's still fairly common to have the opposite.

**Comment by samvermette** [comment]
@Gabro this actually makes a lot of sense now that you explained it. Sorry for dismissing your PR so quick, I'm quick on the feature creep trigger, but in your case this is very sensible. Thanks!

**Comment by gabro** [comment]
Glad to hear that!
You don't need to apologize, actually I love the way all your components stay as simple as possible, and I believe this comes also from rejecting ad-hoc feature requests.

Thank you

PS As I mentioned, I'm working on the inifinity scroll from the top also. It should be completed by next week.

**Comment by kevinrenskers** [comment]
It's too bad you can't have pull to refresh on the top AND bottom. In detail views this would be perfect for triggering a go to previous/next article action. It would also be necessary to have custom titles for both pull to refresh views of course.

**Comment by TeknoloGenie** [comment]
what would it take to accomplish using both top and bottom at the same time?

**Comment by taher-mosbah** [comment]
Hello, is there any chance we can have pull to refresh from top and bottom at the same time ?

**Comment by liruqi** [comment]
@kevinrenskers @TeknoloGenie @taher-mosbah 
Check out #158
The implementation is not so elegant but you may try it out. It worked fine for me.

**Pull request merged**
