### PR TITLE
Respect original content inset when scrolling

### PR DESCRIPTION
**Pull request by fphilipe**
Related issue: #33

### CODE REVIEW

**Comment by fphilipe** [comment]
@samvermette Could you make a new release, please?

**Comment by samvermette** [comment]
@fphilipe what do you mean a new release? You mean on CocoaPods?

**Comment by fphilipe** [comment]
Just bump the version number and tag the git repo with it.

Maybe version 0.3.0 or if you want you can release it as 1.0.0. That’s up to you.

If you want you can add the version to CocoaPods but I can do that quickly since I’m a member of the CocoaPods team.

**Comment by samvermette** [comment]
Tagged the latest commit with 0.3. Thanks!

**Pull request merged**
