### PR TITLE
add explanation to Infinite Scrolling like Pull to Refresh

### PR DESCRIPTION
**Pull request by MarkVillacampa**
I think this might be useful for some people, since it is explained in the Pull to Refresh section but not in the Infinite Scrolling one

### CODE REVIEW

**Comment by samvermette** [comment]
The infinite scrolling doesn't explicitly need to be "stopped", since it always appears below the folder / outside the viewport. I'm actually thinking I should get rid of that method...

**Comment by MarkVillacampa** [comment]
Uhm weird, my UIScrollView is not loading any results past the first time addInfiniteScrollingWithActionHandler is fired, unless I call stopAnimating from within.

The app will be open sourced in a few days, so I'll it here so that you can have a quick look.

Thanks!

**Comment by MarkVillacampa** [comment]
So, is it necessary then?

**Comment by samvermette** [comment]
Until I fix the behavior you reported I guess it is. Calling `stopAnimating` resets the view's state, which will allow it to be triggered again later.

**Pull request merged**
