### PR TITLE
Added last updated label underneath title label. Minor layout tweak to accomodate new label

### PR DESCRIPTION
**Pull request by colinhumber**
Last updated date is updated after the actionHandler block is completed. Label is updated as the refresh view hides.

### CODE REVIEW

**Comment by samvermette** [comment]
Thanks for contributing, I wanted to add this feature shortly. However I think the date should be set from outside of SVPullToRefresh, so it can be saved or handled whatever way the developer wants. Let alone persistence through app launch...

**Comment by colinhumber** [comment]
Good call. It would be pretty trivial for the dev to just set a property after a data load, etc.

**Comment by ghost** [comment]
Surely this should be optional?

There a use cases where pull to refresh fits but doesn't require the display of the last updated date.

**Comment by samvermette** [comment]
@micpringle yes, the date label would only appear if you were to set the `date` property. Will finalize this pull request shortly...

**Comment by ghost** [comment]
@samvermette Thanks for the clarification.

**Comment by samvermette** [comment]
Just merged this and did a small clean up so the view can also be shown without the date label.

Should there be a way to set the `dateFormatter`'s date and time style to alter how the date is displayed in the date label?

**Pull request merged**
